id: P003069
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS18460
  title: སྨན་དཔྱད་བདུད་རྩའི་བུམ་པ།
  author: ''
  volumes:
    6bac68029bca4e76b2e400a689925a6e:
      image_group_id: I8LS18462
      title: ''
      volume_number: 1
      total_pages: 389
      base_file: v001.txt
