id: I9B68E59E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T07:38:09+00:00'
last_modified: '2022-06-07T17:20:53.188446+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18460
  title: སྨན་དཔྱད་བདུད་རྩའི་བུམ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1D27:
      image_group_id: I8LS18462
      title: ''
      total_pages: 389
      order: 1
      base_file: 1D27.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
